<a href="https://colab.research.google.com/github/kailynforsythe/Opioid-Crisis/blob/main/ingestions/notebooks/cleaning_opioid_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df = pd.read_csv("nsduh.csv")
df.head()

/tmp/ipykernel_3726/85395855.py:2: DtypeWarning: Columns (2281) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("nsduh.csv")

,YEAR,AGE3,PDEN10,NEWRACE2,IRINSUR4,IRHHSIZ2,IRPINC3,IRFAMIN3,IRKI17_2,IRHH65_2,...,ANYNEDFLAG,ANYNEDYR,FPIMFNMYR,ILIMFOTHFG,ILIMFOTHYR,ILIMFOTHMN,ANALWT2_C1,ANALWT2_C2,ANALWT2_C3,ANALWT2_C4
0,2021,8,2,1,1,2,2,2,2,1,...,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,732.884779,366.442389,244.294926,183.221195
1,2021,11,1,1,1,2,7,7,1,3,...,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,11710.016142,5855.008071,3903.338714,2927.504035
2,2021,6,2,1,1,2,1,4,1,1,...,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,466.934414,233.467207,155.644805,116.733603
3,2021,9,1,1,1,3,1,3,2,1,...,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,11070.439576,5535.219788,3690.146525,2767.609894
4,2021,6,1,7,2,1,1,1,1,1,...,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,218.379769,109.189885,72.793256,54.594942

In [ ]:
columns_to_filter = [
    'SERVICE', 'MILSTAT', 'NOMARR2', 'LVLDIFMEM2', 'LVLDIFCARE2', 'IRSEX',
    'IREDUHIGHST2', 'SEXAGE', 'HEALTH2', 'EDUSCKMON', 'EDUSKPMON', 'WRKDRGPOL',
    'WRKDRGEDU', 'WRKTSTALC', 'WRKTSTRDM', 'WRKOKPREH', 'WRKOKRAND', 'WRKSTATWK2',
    'IMOTHER', 'IFATHER', 'IRHH65_2', 'IRFAMSOC', 'IRFAMSSI', 'IRFSTAMP',
    'IRFAMPMT', 'IRFAMSVC', 'IRPINC3', 'GOVTPROG', 'BOOKED', 'BKSRVIOL',
    'BKSMASLT', 'BKPOSTOB', 'BKDRVINF', 'BKDRUG', 'PNRNMLAS1', 'OPINMMON', 'FUPNRNM18', 'OPINMYR'
]

# Filter the DataFrame to include only the specified columns
df_filtered = df[columns_to_filter]
df_opinmyr = df_filtered[df_filtered['OPINMYR'] == 1]
df_opinmyr.head()

# Save the filtered DataFrame to a CSV file
df_filtered.to_csv('filtered_nsduh.csv', index=False)

print("Filtered data saved to 'filtered_nsduh.csv'")
df_filtered.head()

Filtered data saved to 'filtered_nsduh.csv'

,SERVICE,MILSTAT,NOMARR2,LVLDIFMEM2,LVLDIFCARE2,IRSEX,IREDUHIGHST2,SEXAGE,HEALTH2,EDUSCKMON,...,BOOKED,BKSRVIOL,BKSMASLT,BKPOSTOB,BKDRVINF,BKDRUG,PNRNMLAS1,OPINMMON,FUPNRNM18,OPINMYR
0,2,99,99,1,1,2,9,5,4.0,99,...,2,99,99,99,99,99,91,0.0,2.0,0.0
1,2,99,1,1,1,1,11,5,3.0,99,...,2,99,99,99,99,99,91,0.0,2.0,0.0
2,2,99,99,1,1,2,11,4,2.0,99,...,2,99,99,99,99,99,91,0.0,2.0,0.0
3,2,99,99,2,1,1,6,5,2.0,99,...,2,99,99,99,99,99,91,0.0,2.0,0.0
4,2,99,99,1,1,1,8,3,1.0,99,...,2,99,99,99,99,99,91,0.0,2.0,0.0

In [ ]:
df_opinmyr = df_filtered[df_filtered['OPINMYR'] == 1]
df_opinmyr.head()

,SERVICE,MILSTAT,NOMARR2,LVLDIFMEM2,LVLDIFCARE2,IRSEX,IREDUHIGHST2,SEXAGE,HEALTH2,EDUSCKMON,...,BOOKED,BKSRVIOL,BKSMASLT,BKPOSTOB,BKDRVINF,BKDRUG,PNRNMLAS1,OPINMMON,FUPNRNM18,OPINMYR
25,2,99,1,2,1,1,10,5,2.0,99,...,1,99,99,99,99,99,10,0.0,2.0,1.0
109,2,99,99,3,3,2,7,2,4.0,0,...,2,99,99,99,99,99,17,1.0,1.0,1.0
115,1,3,99,2,1,1,9,5,4.0,99,...,1,99,99,99,99,99,25,0.0,2.0,1.0
127,2,99,1,2,1,1,11,5,2.0,99,...,1,99,99,99,99,99,1,1.0,2.0,1.0
132,2,99,99,1,1,1,8,3,3.0,99,...,1,2,2,99,1,1,26,1.0,2.0,1.0

In [ ]:
num_rows_opinmyr = df_opinmyr.shape[0]
print(f"The DataFrame df_opinmyr has {num_rows_opinmyr} rows.")

The DataFrame df_opinmyr has 61 rows.